development:
  adapter: mysql
  encoding: utf8
  database: bancouni_tematic
  username: root
  password:
  host: localhost
test:
  adapter: mysql
  encoding: utf8
  database: banco_tematico_test
  username: root
  password:
  host: localhost
production:
  adapter: mysql
  encoding: utf8
  database: bancouni_tematic
  username: root
  password:
  host: localhost
